# Generated by Django 6.1.1 on 2026-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_pf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_esi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_esi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_tds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_tds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
