# Generated by Django 6.1.1 on 2026-10-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_employeechangehistory_employeesalaryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechangehistory',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
