# Generated by Django 6.1.1 on 2026-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeechangehistory_correlation_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeesalaryhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('employee',), name='unique_active_salary_per_employee'),
        ),
    ]
