# Generated by Django 6.1.1 on 2026-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeesalaryhistory_unique_active_salary_per_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='correlation_id',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
