# Generated by Django 6.1.1 on 2026-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_idempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
